# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  chisel = {
    pname = "chisel";
    version = "892fa8020aa329274a85f782b252cad6a32a9f4d";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel";
      rev = "892fa8020aa329274a85f782b252cad6a32a9f4d";
      fetchSubmodules = false;
      sha256 = "sha256-+uGGThfIYiQtbXARj1FThCowh07kNwmxbhaZhkKhoL4=";
    };
    date = "2024-11-26";
  };
}
